### ISSUE TITLE
Build the apk in CI pipeline

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#62]
# Description
We don't have any tests right now, but we can build the `apk` to check if the app is doing well or not. Add another step in the workflow to build the apk.

# Relevant files
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/.github/workflows/Test.push.yml

# Screenshot
Please attach screenshots for the same, if applicable

# References
- https://github.com/subosito/flutter-action
```yaml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: 'zulu'
    java-version: '11'
- uses: subosito/flutter-action@v1
  with:
    channel: 'stable' # or: 'beta', 'dev' or 'master'
- run: flutter pub get
- run: flutter test
- run: flutter build apk
```
